# Generated by Django 5.2.5 on 2025-08-12 08:51

import apps.module.tally.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_module_alter_organization_options_organizationmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Parent Ledger',
                'verbose_name_plural': 'Parent Ledgers',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('master_id', models.CharField(blank=True, max_length=255, null=True)),
                ('alter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_balance', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_in', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_ledgers', to='tally.parentledger')),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledgers',
            },
        ),
        migrations.CreateModel(
            name='TallyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cgst_parents', models.ManyToManyField(blank=True, related_name='cgst_tally_configs', to='tally.parentledger', verbose_name='CGST Parent Ledgers')),
                ('chart_of_accounts_expense_parents', models.ManyToManyField(blank=True, related_name='ex_coa_tally_configs', to='tally.parentledger', verbose_name='Expense COA Parent Ledgers')),
                ('chart_of_accounts_parents', models.ManyToManyField(blank=True, related_name='coa_tally_configs', to='tally.parentledger', verbose_name='COA Parent Ledgers')),
                ('igst_parents', models.ManyToManyField(blank=True, related_name='igst_tally_configs', to='tally.parentledger', verbose_name='IGST Parent Ledgers')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
                ('sgst_parents', models.ManyToManyField(blank=True, related_name='sgst_tally_configs', to='tally.parentledger', verbose_name='SGST Parent Ledgers')),
                ('vendor_parents', models.ManyToManyField(blank=True, related_name='vendor_tally_configs', to='tally.parentledger', verbose_name='Vendor Parent Ledgers')),
            ],
            options={
                'verbose_name': 'Tally Configuration',
                'verbose_name_plural': 'Tally Configurations',
            },
        ),
        migrations.CreateModel(
            name='TallyExpenseAnalyzedBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('note', models.CharField(blank=True, default='Enter Your Description', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cgst_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cgst_tally_expense_analyzed_bills', to='tally.ledger')),
                ('igst_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='igst_tally_expense_analyzed_bills', to='tally.ledger')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
                ('sgst_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgst_tally_expense_analyzed_bills', to='tally.ledger')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tally_expense_analyzed_bills', to='tally.ledger')),
            ],
            options={
                'verbose_name': 'Tally Expense Analysed Bill',
                'verbose_name_plural': 'Tally Expense Analysed Bills',
            },
        ),
        migrations.CreateModel(
            name='TallyExpenseAnalyzedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_details', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.ledger')),
                ('expense_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tally.tallyexpenseanalyzedbill')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Tally Expense Analysed Bill Product',
                'verbose_name_plural': 'Tally Expense Analysed Bill Products',
            },
        ),
        migrations.CreateModel(
            name='TallyExpenseBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billmunshiName', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='bills/', validators=[apps.module.tally.models.validate_file_extension])),
                ('fileType', models.CharField(blank=True, choices=[('Single Invoice/File', 'Single Invoice/File'), ('Multiple Invoice/File', 'Multiple Invoice/File')], default='Single Invoice/File', max_length=100, null=True)),
                ('analysed_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analysed', 'Analysed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10)),
                ('process', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Tally Expense Bill',
                'verbose_name_plural': 'Tally Expense Bills',
            },
        ),
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='selectBill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysed_headers', to='tally.tallyexpensebill'),
        ),
        migrations.CreateModel(
            name='TallyVendorAnalyzedBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('gst_type', models.CharField(choices=[('Intra-State', 'Intra-State'), ('Inter-State', 'Inter-State'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('note', models.TextField(blank=True, default='Enter Your Description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cgst_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cgst_tally_vendor_analyzed_bills', to='tally.ledger')),
                ('igst_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='igst_tally_vendor_analyzed_bills', to='tally.ledger')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
                ('sgst_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgst_tally_vendor_analyzed_bills', to='tally.ledger')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tally_vendor_analyzed_bills', to='tally.ledger')),
            ],
            options={
                'verbose_name': 'Tally Vendor Analysed Bill',
                'verbose_name_plural': 'Tally Vendor Analysed Bills',
            },
        ),
        migrations.CreateModel(
            name='TallyVendorAnalyzedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_details', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_gst', models.CharField(blank=True, choices=[('0%', '0%'), ('5%', '5%'), ('12%', '12%'), ('18%', '18%'), ('28%', '28%'), ('Exempted', 'Exempted'), ('N/A', 'N/A')], max_length=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
                ('taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.ledger')),
                ('vendor_bill_analyzed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tally.tallyvendoranalyzedbill')),
            ],
            options={
                'verbose_name': 'Tally Analysed Bill Product',
                'verbose_name_plural': 'Tally Analysed Bill Products',
            },
        ),
        migrations.CreateModel(
            name='TallyVendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billmunshiName', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='bills/', validators=[apps.module.tally.models.validate_file_extension])),
                ('fileType', models.CharField(blank=True, choices=[('Single Invoice/File', 'Single Invoice/File'), ('Multiple Invoice/File', 'Multiple Invoice/File')], default='Single Invoice/File', max_length=100, null=True)),
                ('analysed_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analysed', 'Analysed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10)),
                ('process', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Tally Vendor Bill',
                'verbose_name_plural': 'Tally Vendor Bills',
            },
        ),
        migrations.AddField(
            model_name='tallyvendoranalyzedbill',
            name='selectBill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysed_headers', to='tally.tallyvendorbill'),
        ),
        migrations.AddIndex(
            model_name='parentledger',
            index=models.Index(fields=['organization', 'parent'], name='tally_paren_organiz_d288f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentledger',
            unique_together={('organization', 'parent')},
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['organization', 'name'], name='tally_ledge_organiz_606a87_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['organization', 'master_id'], name='tally_ledge_organiz_e4931a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tallyconfig',
            unique_together={('organization',)},
        ),
        migrations.AddIndex(
            model_name='tallyexpenseanalyzedproduct',
            index=models.Index(fields=['organization', 'created_at'], name='tally_tally_organiz_96d90b_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyexpensebill',
            index=models.Index(fields=['organization', 'status'], name='tally_tally_organiz_a1ff4c_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyexpensebill',
            index=models.Index(fields=['organization', 'created_at'], name='tally_tally_organiz_4b609b_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyexpenseanalyzedbill',
            index=models.Index(fields=['organization', 'created_at'], name='tally_tally_organiz_d5f747_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyvendoranalyzedproduct',
            index=models.Index(fields=['organization', 'created_at'], name='tally_tally_organiz_82b7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyvendorbill',
            index=models.Index(fields=['organization', 'status'], name='tally_tally_organiz_ca6cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyvendorbill',
            index=models.Index(fields=['organization', 'created_at'], name='tally_tally_organiz_72cb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='tallyvendoranalyzedbill',
            index=models.Index(fields=['organization', 'created_at'], name='tally_tally_organiz_d91694_idx'),
        ),
    ]
