# Generated by Django 5.2.5 on 2025-08-12 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ledger',
            name='tally_ledge_organiz_606a87_idx',
        ),
        migrations.RemoveIndex(
            model_name='ledger',
            name='tally_ledge_organiz_e4931a_idx',
        ),
        migrations.RemoveIndex(
            model_name='parentledger',
            name='tally_paren_organiz_d288f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='tallyexpenseanalyzedbill',
            name='tally_tally_organiz_d5f747_idx',
        ),
        migrations.RemoveIndex(
            model_name='tallyexpenseanalyzedproduct',
            name='tally_tally_organiz_96d90b_idx',
        ),
        migrations.RemoveIndex(
            model_name='tallyexpensebill',
            name='tally_tally_organiz_a1ff4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='tallyexpensebill',
            name='tally_tally_organiz_4b609b_idx',
        ),
        migrations.RemoveIndex(
            model_name='tallyvendoranalyzedbill',
            name='tally_tally_organiz_d91694_idx',
        ),
        migrations.RemoveIndex(
            model_name='tallyvendoranalyzedproduct',
            name='tally_tally_organiz_82b7aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='tallyvendorbill',
            name='tally_tally_organiz_ca6cc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='tallyvendorbill',
            name='tally_tally_organiz_72cb7d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parentledger',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tallyconfig',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='tally.parentledger'),
        ),
        migrations.AlterField(
            model_name='parentledger',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tallyconfig',
            name='chart_of_accounts_expense_parents',
            field=models.ManyToManyField(blank=True, related_name='expense_coa_tally_configs', to='tally.parentledger', verbose_name='Expense COA Parent Ledgers'),
        ),
        migrations.AlterField(
            model_name='tallyconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tallyexpenseanalyzedbill',
            name='cgst_taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cgst_tally_expense_analysed_bills', to='tally.ledger'),
        ),
        migrations.AlterField(
            model_name='tallyexpenseanalyzedbill',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tallyexpenseanalyzedbill',
            name='igst_taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='igst_tally_expense_analysed_bills', to='tally.ledger'),
        ),
        migrations.AlterField(
            model_name='tallyexpenseanalyzedbill',
            name='sgst_taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgst_tally_expense_analysed_bills', to='tally.ledger'),
        ),
        migrations.AlterField(
            model_name='tallyexpenseanalyzedbill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_tally_expense_analysed_bills', to='tally.ledger'),
        ),
        migrations.AlterField(
            model_name='tallyexpenseanalyzedproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tallyexpensebill',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedbill',
            name='cgst_taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cgst_tally_vendor_analysed_bills', to='tally.ledger'),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedbill',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedbill',
            name='igst_taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='igst_tally_vendor_analysed_bills', to='tally.ledger'),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedbill',
            name='sgst_taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgst_tally_vendor_analysed_bills', to='tally.ledger'),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedbill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_tally_vendor_analysed_bills', to='tally.ledger'),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tallyvendorbill',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
