# Generated by Django 5.2.5 on 2025-09-02 09:43

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentledger',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tallyexpenseanalyzedbill',
            old_name='selectBill',
            new_name='selected_bill',
        ),
        migrations.RenameField(
            model_name='tallyexpensebill',
            old_name='billmunshiName',
            new_name='bill_munshi_name',
        ),
        migrations.RenameField(
            model_name='tallyexpensebill',
            old_name='fileType',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='tallyvendoranalyzedbill',
            old_name='selectBill',
            new_name='selected_bill',
        ),
        migrations.RenameField(
            model_name='tallyvendorbill',
            old_name='billmunshiName',
            new_name='bill_munshi_name',
        ),
        migrations.RenameField(
            model_name='tallyvendorbill',
            old_name='fileType',
            new_name='file_type',
        ),
        migrations.AddField(
            model_name='ledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=15, null=True),
        ),
    ]
