# Generated by Django 5.2.5 on 2025-09-15 13:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tally", "0002_rename_update_at_parentledger_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tallyvendoranalyzedbill",
            name="cgst",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tallyvendoranalyzedbill",
            name="igst",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tallyvendoranalyzedbill",
            name="sgst",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tallyvendoranalyzedbill",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                null=True,
            ),
        ),
    ]
