# Generated by Django 5.2.5 on 2025-09-16 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_organizationmodule_options_and_more"),
        ("tally", "0003_alter_tallyvendoranalyzedbill_cgst_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("master_id", models.CharField(blank=True, max_length=255, null=True)),
                ("alter_id", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("parent", models.CharField(blank=True, max_length=255, null=True)),
                ("unit", models.CharField(blank=True, max_length=100, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gst_applicable",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("item_code", models.CharField(blank=True, max_length=255, null=True)),
                ("alias", models.CharField(blank=True, max_length=255, null=True)),
                ("company", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tally_%(class)ss",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Item",
                "verbose_name_plural": "Stock Items",
                "unique_together": {("organization", "master_id", "company")},
            },
        ),
    ]
