# Generated by Django 5.2.5 on 2025-09-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0004_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='gst_type',
            field=models.CharField(choices=[('IGST', 'IGST'), ('CGST_SGST', 'CGST+SGST'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
