# Generated by Django 5.2.5 on 2025-09-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0005_tallyexpenseanalyzedbill_gst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='cgst_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='igst_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='sgst_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10, null=True),
        ),
    ]
