# Generated by Django 5.2.5 on 2025-09-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0006_tallyexpenseanalyzedbill_cgst_debit_or_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='vendor_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tallyexpenseanalyzedbill',
            name='cgst_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tallyexpenseanalyzedbill',
            name='igst_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tallyexpenseanalyzedbill',
            name='sgst_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tallyexpenseanalyzedproduct',
            name='debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True),
        ),
    ]
