# Generated by Django 5.2.5 on 2025-09-23 16:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0007_tallyexpenseanalyzedbill_vendor_debit_or_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='vendor_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
    ]
