# Generated by Django 5.2.5 on 2025-10-02 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0008_tallyexpenseanalyzedbill_vendor_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpensebill',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this expense bill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tally_expense_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this vendor bill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tally_vendor_bills', to=settings.AUTH_USER_MODEL),
        ),
    ]
