# Generated by Django 5.2.5 on 2025-10-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0009_tallyexpensebill_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallyconfig',
            name='cgst_parents',
            field=models.ManyToManyField(blank=True, db_table='tally_config_cgst_parents', related_name='cgst_tally_configs', to='tally.parentledger', verbose_name='CGST Parent Ledgers'),
        ),
        migrations.AlterField(
            model_name='tallyconfig',
            name='chart_of_accounts_expense_parents',
            field=models.ManyToManyField(blank=True, db_table='tally_config_expense_coa_parents', related_name='expense_coa_tally_configs', to='tally.parentledger', verbose_name='Expense COA Parent Ledgers'),
        ),
        migrations.AlterField(
            model_name='tallyconfig',
            name='chart_of_accounts_parents',
            field=models.ManyToManyField(blank=True, db_table='tally_config_coa_parents', related_name='coa_tally_configs', to='tally.parentledger', verbose_name='COA Parent Ledgers'),
        ),
        migrations.AlterField(
            model_name='tallyconfig',
            name='igst_parents',
            field=models.ManyToManyField(blank=True, db_table='tally_config_igst_parents', related_name='igst_tally_configs', to='tally.parentledger', verbose_name='IGST Parent Ledgers'),
        ),
        migrations.AlterField(
            model_name='tallyconfig',
            name='sgst_parents',
            field=models.ManyToManyField(blank=True, db_table='tally_config_sgst_parents', related_name='sgst_tally_configs', to='tally.parentledger', verbose_name='SGST Parent Ledgers'),
        ),
        migrations.AlterField(
            model_name='tallyconfig',
            name='vendor_parents',
            field=models.ManyToManyField(blank=True, db_table='tally_config_vendor_parents', related_name='vendor_tally_configs', to='tally.parentledger', verbose_name='Vendor Parent Ledgers'),
        ),
    ]
