# Generated by Django 5.2.5 on 2025-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0010_alter_tallyconfig_cgst_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyconfig',
            name='tally_product_allow_sync',
            field=models.BooleanField(default=False),
        ),
    ]
