# Generated by Django 5.2.5 on 2025-10-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0011_tallyconfig_tally_product_allow_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallyexpenseanalyzedproduct',
            name='item_details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedproduct',
            name='item_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
