# Generated by Django 5.2.5 on 2025-10-11 19:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0012_alter_tallyexpenseanalyzedproduct_item_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallyexpenseanalyzedproduct',
            name='debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedproduct',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedproduct',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedproduct',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedproduct',
            name='product_gst',
            field=models.CharField(blank=True, choices=[('0%', '0%'), ('5%', '5%'), ('12%', '12%'), ('18%', '18%'), ('28%', '28%'), ('Exempted', 'Exempted'), ('N/A', 'N/A')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tallyvendoranalyzedproduct',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=50, null=True),
        ),
    ]
