# Generated by Django 5.2.5 on 2025-10-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationapikey_api_key_value_gen'),
        ('tally', '0013_alter_tallyexpenseanalyzedproduct_debit_or_credit_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(condition=models.Q(('master_id__isnull', False), models.Q(('master_id', ''), _negated=True)), fields=('master_id', 'organization'), name='unique_master_id_per_organization'),
        ),
    ]
