# Generated by Django 5.2.5 on 2025-10-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0014_ledger_unique_master_id_per_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tallyvendoranalyzedbill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
