# Generated by Django 5.2.5 on 2025-12-21 06:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationapikey_api_key_value_gen'),
        ('tally', '0015_tallyexpenseanalyzedbill_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='consolidate',
            field=models.BooleanField(default=False, help_text='If True, sync as single consolidated expense entry. If False, sync all individual entries.'),
        ),
        migrations.AddField(
            model_name='tallyvendoranalyzedbill',
            name='consolidate',
            field=models.BooleanField(default=False, help_text='If True, sync as single consolidated line item. If False, sync all individual line items.'),
        ),
        migrations.CreateModel(
            name='TallyExpenseConsolidatedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_details', models.CharField(blank=True, help_text='Consolidated expense item details', max_length=2000, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total consolidated amount', max_digits=12, null=True)),
                ('debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', help_text='Debit or credit for consolidated entry', max_length=50, null=True)),
                ('original_entries_count', models.IntegerField(default=0, help_text='Number of original expense entries that were consolidated')),
                ('consolidation_notes', models.TextField(blank=True, help_text='Notes about how consolidation was performed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_of_accounts', models.ForeignKey(blank=True, help_text='Primary chart of accounts for consolidated entry', null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.ledger')),
                ('expense_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_product', to='tally.tallyexpenseanalyzedbill')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Consolidated Tally Expense Product',
                'verbose_name_plural': 'Consolidated Tally Expense Products',
            },
        ),
        migrations.CreateModel(
            name='TallyVendorConsolidatedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(blank=True, help_text='Consolidated item name', max_length=2000, null=True)),
                ('item_details', models.TextField(blank=True, help_text='Detailed breakdown of consolidated items', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Consolidated rate/price', max_digits=50, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, help_text='Usually 1 for consolidated items', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total consolidated amount', max_digits=50, null=True)),
                ('product_gst', models.CharField(blank=True, choices=[('0%', '0%'), ('5%', '5%'), ('12%', '12%'), ('18%', '18%'), ('28%', '28%'), ('Exempted', 'Exempted'), ('N/A', 'N/A')], help_text='Most common GST rate from consolidated items', max_length=50, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total IGST amount', max_digits=50, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total CGST amount', max_digits=50, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Total SGST amount', max_digits=50, null=True)),
                ('original_items_count', models.IntegerField(default=0, help_text='Number of original line items that were consolidated')),
                ('consolidation_notes', models.TextField(blank=True, help_text='Notes about how consolidation was performed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
                ('taxes', models.ForeignKey(blank=True, help_text='Primary tax ledger for consolidated item', null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.ledger')),
                ('vendor_bill_analyzed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_product', to='tally.tallyvendoranalyzedbill')),
            ],
            options={
                'verbose_name': 'Consolidated Tally Vendor Product',
                'verbose_name_plural': 'Consolidated Tally Vendor Products',
            },
        ),
    ]
