# Generated by Django 5.2.5 on 2025-12-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0017_add_tds_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallyexpenseconsolidatedproduct',
            name='expense_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_products', to='tally.tallyexpenseanalyzedbill'),
        ),
        migrations.AlterField(
            model_name='tallyvendorconsolidatedproduct',
            name='vendor_bill_analyzed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_products', to='tally.tallyvendoranalyzedbill'),
        ),
    ]
