# Generated by Django 5.2.5 on 2026-01-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0018_alter_tallyexpenseconsolidatedproduct_expense_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpensebill',
            name='duplicate_description',
            field=models.TextField(blank=True, help_text='Description of duplicate matches found', null=True),
        ),
        migrations.AddField(
            model_name='tallyexpensebill',
            name='duplicate_matched_bills',
            field=models.JSONField(blank=True, default=list, help_text='List of matched duplicate bill details'),
        ),
        migrations.AddField(
            model_name='tallyexpensebill',
            name='duplicate_score',
            field=models.FloatField(blank=True, help_text='Similarity score with duplicate bills (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='tallyexpensebill',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='Whether this bill is identified as a potential duplicate'),
        ),
        migrations.AddField(
            model_name='tallyexpensebill',
            name='is_processing',
            field=models.BooleanField(default=False, help_text='Whether this bill is currently being processed in background'),
        ),
        migrations.AddField(
            model_name='tallyexpensebill',
            name='job_id',
            field=models.CharField(blank=True, help_text='Background job ID for tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tallyexpensebill',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='duplicate_description',
            field=models.TextField(blank=True, help_text='Description of duplicate matches found', null=True),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='duplicate_matched_bills',
            field=models.JSONField(blank=True, default=list, help_text='List of matched duplicate bill details'),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='duplicate_score',
            field=models.FloatField(blank=True, help_text='Similarity score with duplicate bills (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='Whether this bill is identified as a potential duplicate'),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='is_processing',
            field=models.BooleanField(default=False, help_text='Whether this bill is currently being processed in background'),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='job_id',
            field=models.CharField(blank=True, help_text='Background job ID for tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
    ]
