# Generated by Django 5.2.5 on 2026-01-08 18:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0019_tallyexpensebill_duplicate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='other_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='other_adjustment_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='other_adjustment_taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_adjustment_tally_expense_analysed_bills', to='tally.ledger'),
        ),
    ]
