# Generated by Django 5.2.5 on 2026-01-18 17:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0020_tallyexpenseanalyzedbill_other_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyconfig',
            name='payment_parents',
            field=models.ManyToManyField(blank=True, db_table='tally_config_payment_parents', related_name='payment_tally_configs', to='tally.parentledger', verbose_name='Payment Parent Ledgers'),
        ),
        migrations.AddField(
            model_name='tallyconfig',
            name='tds_parents',
            field=models.ManyToManyField(blank=True, db_table='tally_config_tds_parents', related_name='tds_tally_configs', to='tally.parentledger', verbose_name='TDS Parent Ledgers'),
        ),
        migrations.AddField(
            model_name='tallyvendoranalyzedbill',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tallyvendoranalyzedbill',
            name='discount_taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_tally_vendor_analysed_bills', to='tally.ledger'),
        ),
    ]
