# Generated by Django 5.2.5 on 2026-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0021_tallyconfig_payment_parents_tallyconfig_tds_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpensebill',
            name='tally_synced',
            field=models.BooleanField(default=False, help_text='Whether this bill has been synced with Tally'),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='tally_synced',
            field=models.BooleanField(default=False, help_text='Whether this bill has been synced with Tally'),
        ),
    ]
