# Generated by Django 5.2.5 on 2026-02-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0022_tallyexpensebill_tally_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpensebill',
            name='bill_belong_your_org',
            field=models.BooleanField(default=False, help_text='Whether this bill belongs to your organization'),
        ),
        migrations.AddField(
            model_name='tallyexpensebill',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the bill', null=True),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='bill_belong_your_org',
            field=models.BooleanField(default=False, help_text='Whether this bill belongs to your organization'),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the bill', null=True),
        ),
    ]
