# Generated by Django 6.0.2 on 2026-03-20 18:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tally", "0023_tallyexpensebill_bill_belong_your_org_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tallyvendoranalyzedbill",
            name="cess",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tallyvendoranalyzedbill",
            name="cess_taxes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cess_tally_vendor_analysed_bills",
                to="tally.ledger",
            ),
        ),
        migrations.AddField(
            model_name="tallyvendoranalyzedbill",
            name="freight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tallyvendoranalyzedbill",
            name="freight_taxes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freight_tally_vendor_analysed_bills",
                to="tally.ledger",
            ),
        ),
    ]
