# Generated by Django 6.0.2 on 2026-05-01 17:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tally", "0025_tallyexpensebill_tally_sync_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tallyconfig",
            name="round_off_parents",
            field=models.ManyToManyField(
                blank=True,
                db_table="tally_config_round_off_parents",
                help_text="Parent ledgers (typically 'Indirect Expenses') used to source the Round Off ledger.",
                related_name="round_off_tally_configs",
                to="tally.parentledger",
                verbose_name="Round Off Parent Ledgers",
            ),
        ),
        migrations.AddField(
            model_name="tallyexpenseanalyzedbill",
            name="round_off",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tallyexpenseanalyzedbill",
            name="round_off_debit_or_credit",
            field=models.CharField(
                blank=True,
                choices=[("credit", "Credit"), ("debit", "Debit")],
                default="debit",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tallyexpenseanalyzedbill",
            name="round_off_taxes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_off_tally_expense_analysed_bills",
                to="tally.ledger",
            ),
        ),
        migrations.AddField(
            model_name="tallyvendoranalyzedbill",
            name="round_off",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tallyvendoranalyzedbill",
            name="round_off_taxes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_off_tally_vendor_analysed_bills",
                to="tally.ledger",
            ),
        ),
    ]
