# Generated by Django 6.0.2 on 2026-05-02 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_organization_gst_number"),
        ("tally", "0028_tallytcprelease"),
    ]

    operations = [
        migrations.CreateModel(
            name="GstRateLedgerMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="GST rate as a percentage (e.g. 18.00 means 18%).",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GST Rate Ledger Mapping",
                "verbose_name_plural": "GST Rate Ledger Mappings",
                "ordering": ["rate"],
            },
        ),
        migrations.RenameIndex(
            model_name="tallysetupstep",
            new_name="tally_tally_is_acti_8ffb8e_idx",
            old_name="tally_tally_is_acti_3a1b9c_idx",
        ),
        migrations.RenameIndex(
            model_name="tallytcprelease",
            new_name="tally_tally_is_acti_2607d9_idx",
            old_name="tally_tally_is_acti_tcp_idx",
        ),
        migrations.AddField(
            model_name="tallyvendoranalyzedproduct",
            name="cgst_ledger",
            field=models.ForeignKey(
                blank=True,
                help_text="Per-line CGST tax ledger (resolved from rate mapping or chosen manually).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cgst_tally_vendor_products",
                to="tally.ledger",
            ),
        ),
        migrations.AddField(
            model_name="tallyvendoranalyzedproduct",
            name="igst_ledger",
            field=models.ForeignKey(
                blank=True,
                help_text="Per-line IGST tax ledger.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="igst_tally_vendor_products",
                to="tally.ledger",
            ),
        ),
        migrations.AddField(
            model_name="tallyvendoranalyzedproduct",
            name="sgst_ledger",
            field=models.ForeignKey(
                blank=True,
                help_text="Per-line SGST tax ledger.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sgst_tally_vendor_products",
                to="tally.ledger",
            ),
        ),
        migrations.AddField(
            model_name="gstrateledgermapping",
            name="cgst_ledger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cgst_rate_mappings",
                to="tally.ledger",
            ),
        ),
        migrations.AddField(
            model_name="gstrateledgermapping",
            name="igst_ledger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="igst_rate_mappings",
                to="tally.ledger",
            ),
        ),
        migrations.AddField(
            model_name="gstrateledgermapping",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tally_%(class)ss",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="gstrateledgermapping",
            name="sgst_ledger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sgst_rate_mappings",
                to="tally.ledger",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gstrateledgermapping",
            unique_together={("organization", "rate")},
        ),
    ]
