# Generated by Django 6.0.7 on 2026-07-20 17:46

import apps.common.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_gst_number'),
        ('tally', '0033_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallyexpensebill',
            name='process',
            field=models.BooleanField(default=False, help_text='HAS-been-analysed flag: True once AI analysis has produced ``analysed_data`` and an ``analysed_headers`` row. Semantically means "analysis done", not "currently processing". For the in-progress state see ``is_processing``. Historical name — keep for backwards compat.'),
        ),
        migrations.AlterField(
            model_name='tallyexpensegstline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='tallyvendorbill',
            name='process',
            field=models.BooleanField(default=False, help_text='HAS-been-analysed flag: True once AI analysis has produced ``analysed_data`` and an ``analysed_headers`` row. Semantically means "analysis done", not "currently processing". For the in-progress state see ``is_processing``. Historical name — keep for backwards compat.'),
        ),
        migrations.CreateModel(
            name='TallyPaymentAnalyzedBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vendor_debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10, null=True)),
                ('vendor_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True)),
                ('voucher', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('gst_type', models.CharField(choices=[('IGST', 'IGST'), ('CGST_SGST', 'CGST+SGST'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True)),
                ('igst_debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True)),
                ('cgst_debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True)),
                ('sgst_debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True)),
                ('tds_debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True)),
                ('other_adjustment', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True)),
                ('other_adjustment_debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True)),
                ('round_off', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True)),
                ('round_off_debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True)),
                ('note', models.CharField(blank=True, default='Enter Your Description', max_length=100, null=True)),
                ('consolidate', models.BooleanField(default=True, help_text='Payment vouchers default to consolidated line items — most users only care about ledger-level totals in a payment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cgst_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cgst_tally_payment_analysed_bills', to='tally.ledger')),
                ('igst_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='igst_tally_payment_analysed_bills', to='tally.ledger')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
                ('other_adjustment_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_adjustment_tally_payment_analysed_bills', to='tally.ledger')),
                ('round_off_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_off_tally_payment_analysed_bills', to='tally.ledger')),
                ('sgst_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgst_tally_payment_analysed_bills', to='tally.ledger')),
                ('tds_taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_tally_payment_analysed_bills', to='tally.ledger')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_tally_payment_analysed_bills', to='tally.ledger')),
            ],
            options={
                'verbose_name': 'Tally Payment Analysed Voucher',
                'verbose_name_plural': 'Tally Payment Analysed Vouchers',
            },
        ),
        migrations.CreateModel(
            name='TallyPaymentAnalyzedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_details', models.CharField(blank=True, max_length=2000, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True)),
                ('debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.ledger')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
                ('payment_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tally.tallypaymentanalyzedbill')),
            ],
            options={
                'verbose_name': 'Tally Payment Analysed Voucher Product',
                'verbose_name_plural': 'Tally Payment Analysed Voucher Products',
            },
        ),
        migrations.CreateModel(
            name='TallyPaymentBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bill_munshi_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to=apps.common.validators.bill_upload_path, validators=[apps.common.validators.validate_file_extension, apps.common.validators.validate_bill_file_size])),
                ('file_type', models.CharField(blank=True, choices=[('Single Invoice/File', 'Single Invoice/File'), ('Multiple Invoice/File', 'Multiple Invoice/File')], default='Single Invoice/File', max_length=100, null=True)),
                ('analysed_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analysed', 'Analysed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10)),
                ('process', models.BooleanField(default=False, help_text='HAS-been-analysed flag: True once AI analysis has produced ``analysed_data``.')),
                ('is_duplicate', models.BooleanField(default=False)),
                ('duplicate_description', models.TextField(blank=True, null=True)),
                ('duplicate_score', models.FloatField(blank=True, null=True)),
                ('duplicate_matched_bills', models.JSONField(blank=True, default=list)),
                ('is_processing', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hex digest of the uploaded file for exact-duplicate detection', max_length=64, null=True)),
                ('tally_synced', models.BooleanField(default=False)),
                ('tally_sync_message', models.TextField(blank=True, null=True)),
                ('bill_belong_your_org', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this payment voucher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tally_payment_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tally Payment Voucher',
                'verbose_name_plural': 'Tally Payment Vouchers',
            },
        ),
        migrations.AddField(
            model_name='tallypaymentanalyzedbill',
            name='selected_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysed_headers', to='tally.tallypaymentbill'),
        ),
        migrations.CreateModel(
            name='TallyPaymentConsolidatedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_details', models.CharField(blank=True, max_length=2000, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True)),
                ('debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=50, null=True)),
                ('original_entries_count', models.IntegerField(default=0)),
                ('consolidation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.ledger')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
                ('payment_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_products', to='tally.tallypaymentanalyzedbill')),
            ],
            options={
                'verbose_name': 'Consolidated Tally Payment Product',
                'verbose_name_plural': 'Consolidated Tally Payment Products',
            },
        ),
        migrations.CreateModel(
            name='TallyPaymentGstLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rate', models.CharField(blank=True, default='', max_length=10)),
                ('tax_type', models.CharField(choices=[('CGST', 'CGST'), ('SGST', 'SGST'), ('IGST', 'IGST')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('debit_or_credit', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tally_payment_gst_lines', to='tally.ledger')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_%(class)ss', to='organizations.organization')),
                ('payment_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_lines', to='tally.tallypaymentanalyzedbill')),
            ],
            options={
                'verbose_name': 'Tally Payment GST Line',
                'verbose_name_plural': 'Tally Payment GST Lines',
                'ordering': ['rate', 'tax_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='tallypaymentanalyzedbill',
            constraint=models.UniqueConstraint(condition=models.Q(('selected_bill__isnull', False)), fields=('selected_bill',), name='uq_tally_payment_analyzed_selected_bill'),
        ),
    ]
