# Generated by Django 6.0.7 on 2026-07-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0034_payment_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='source',
            field=models.CharField(choices=[('tally', 'Tally'), ('billmunshi', 'Bill Munshi')], db_index=True, default='tally', help_text='``tally``: imported from Tally, already in sync. ``billmunshi``: created via quick-add flow; sync pending.', max_length=16),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tally_sync_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tally_synced',
            field=models.BooleanField(db_index=True, default=True, help_text='True once Tally has confirmed the record exists on its side.'),
        ),
        migrations.AddField(
            model_name='parentledger',
            name='source',
            field=models.CharField(choices=[('tally', 'Tally'), ('billmunshi', 'Bill Munshi')], db_index=True, default='tally', max_length=16),
        ),
        migrations.AddField(
            model_name='parentledger',
            name='tally_sync_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentledger',
            name='tally_synced',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='gst_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='hsn_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='source',
            field=models.CharField(choices=[('tally', 'Tally'), ('billmunshi', 'Bill Munshi')], db_index=True, default='tally', max_length=16),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='tally_sync_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='tally_synced',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
