# Generated by Django 6.0.7 on 2026-08-07 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0036_tallyexpensebill_uniq_tally_expensebill_org_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpensebill',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the record was moved to trash. Drives the retention countdown.', null=True),
        ),
        migrations.AddField(
            model_name='tallyexpensebill',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved the record to trash.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tallyexpensebill',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True while the record sits in the trash awaiting restore or purge.'),
        ),
        migrations.AddField(
            model_name='tallypaymentbill',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the record was moved to trash. Drives the retention countdown.', null=True),
        ),
        migrations.AddField(
            model_name='tallypaymentbill',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved the record to trash.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tallypaymentbill',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True while the record sits in the trash awaiting restore or purge.'),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the record was moved to trash. Drives the retention countdown.', null=True),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who moved the record to trash.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tallyvendorbill',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True while the record sits in the trash awaiting restore or purge.'),
        ),
    ]
