# Generated by Django 5.2.5 on 2025-08-11 19:08

import apps.module.zoho.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_module_alter_organization_options_organizationmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('billmunshiName', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='bills/', validators=[apps.module.zoho.models.validate_file_extension])),
                ('fileType', models.CharField(blank=True, choices=[('Single Invoice/File', 'Single Invoice/File'), ('Multiple Invoice/File', 'Multiple Invoice/File')], default='Single Invoice/File', max_length=100, null=True)),
                ('analysed_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analysed', 'Analysed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10)),
                ('process', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Expense Bill',
            },
        ),
        migrations.CreateModel(
            name='ExpenseZohoBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('cgst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('sgst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('note', models.CharField(blank=True, default='Enter Your Description', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
                ('selectBill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.expensebill')),
            ],
            options={
                'verbose_name_plural': 'Expense Analysed Bill',
            },
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('billmunshiName', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='bills/', validators=[apps.module.zoho.models.validate_file_extension])),
                ('fileType', models.CharField(blank=True, choices=[('Single Invoice/File', 'Single Invoice/File'), ('Multiple Invoice/File', 'Multiple Invoice/File')], default='Single Invoice/File', max_length=100, null=True)),
                ('analysed_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analysed', 'Analysed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10)),
                ('process', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Vendor Bill',
            },
        ),
        migrations.CreateModel(
            name='Zoho_TDS_TCS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('taxId', models.CharField(max_length=100)),
                ('taxName', models.CharField(max_length=100)),
                ('taxPercentage', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('taxType', models.CharField(blank=True, choices=[('TCS', 'tcs_tax'), ('TDS', 'tds_tax')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Zoho TDS and TCS Taxes',
            },
        ),
        migrations.CreateModel(
            name='VendorZohoBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('cgst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('sgst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('is_tax', models.CharField(blank=True, choices=[('TCS', 'is_tcs_tax'), ('TDS', 'is_tds_tax')], default='TDS', max_length=100, null=True)),
                ('note', models.CharField(blank=True, default='Enter Your Description', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
                ('selectBill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.vendorbill')),
                ('tds_tcs_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zoho_tds_tcs')),
            ],
            options={
                'verbose_name_plural': 'Analysed Bill',
            },
        ),
        migrations.CreateModel(
            name='Zoho_Vendor_Credits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vendor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_credit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_credit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Zoho Vendor Credits',
            },
        ),
        migrations.CreateModel(
            name='ZohoChartOfAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('accountId', models.CharField(max_length=100)),
                ('accountName', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Zoho Chart Of Accounts',
            },
        ),
        migrations.CreateModel(
            name='ZohoCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('clientId', models.CharField(max_length=100)),
                ('clientSecret', models.CharField(max_length=100)),
                ('accessCode', models.CharField(default='Your Access Code', max_length=200)),
                ('organisationId', models.CharField(default='Your organisationId', max_length=100)),
                ('redirectUrl', models.CharField(default='Your Redirect URL', max_length=200)),
                ('accessToken', models.CharField(blank=True, max_length=200, null=True)),
                ('refreshToken', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Zoho Credentials',
            },
        ),
        migrations.CreateModel(
            name='ZohoTaxes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('taxId', models.CharField(max_length=100)),
                ('taxName', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Zoho Taxes',
            },
        ),
        migrations.CreateModel(
            name='VendorZohoProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_details', models.CharField(blank=True, max_length=200, null=True)),
                ('reverse_charge_tax_id', models.BooleanField(default=False)),
                ('itc_eligibility', models.CharField(blank=True, choices=[('eligible', 'Eligible'), ('ineligible_section17', 'Ineligible Section17'), ('ineligible_others', 'Ineligible Others')], default='eligible', max_length=100, null=True)),
                ('rate', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
                ('zohoBill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='zoho.vendorzohobill')),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohochartofaccount')),
                ('taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohotaxes')),
            ],
            options={
                'verbose_name_plural': 'Analysed Bill Products',
            },
        ),
        migrations.CreateModel(
            name='ZohoVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contactId', models.CharField(max_length=100, unique=True)),
                ('companyName', models.CharField(max_length=100)),
                ('gstNo', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Zoho Vendor',
            },
        ),
        migrations.AddField(
            model_name='vendorzohobill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohovendor'),
        ),
        migrations.CreateModel(
            name='ExpenseZohoProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_details', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('debit_or_credit', models.CharField(blank=True, choices=[('credit', 'credit'), ('debit', 'debit')], default='credit', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
                ('zohoBill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='zoho.expensezohobill')),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohochartofaccount')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohovendor')),
            ],
            options={
                'verbose_name_plural': 'Expense Analysed Bill Products',
            },
        ),
        migrations.AddField(
            model_name='expensezohobill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohovendor'),
        ),
    ]
