# Generated by Django 5.2.5 on 2025-10-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0002_expensebill_uploaded_by_vendorbill_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensezohoproduct',
            name='item_details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='vendorzohoproduct',
            name='item_details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='vendorzohoproduct',
            name='item_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
