# Generated by Django 5.2.5 on 2025-10-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0003_alter_expensezohoproduct_item_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensezohoproduct',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorzohoproduct',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorzohoproduct',
            name='quantity',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorzohoproduct',
            name='rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
