# Generated by Django 5.2.5 on 2025-10-22 12:03

import apps.module.zoho.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationapikey_api_key_value_gen'),
        ('zoho', '0004_alter_expensezohoproduct_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensezohoproduct',
            name='debit_or_credit',
        ),
        migrations.RemoveField(
            model_name='expensezohoproduct',
            name='vendor',
        ),
        migrations.AddField(
            model_name='expensezohoproduct',
            name='itc_eligibility',
            field=models.CharField(blank=True, choices=[('eligible', 'Eligible'), ('ineligible_section17', 'Ineligible Section17'), ('ineligible_others', 'Ineligible Others')], default='eligible', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensezohoproduct',
            name='reverse_charge_tax_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensezohoproduct',
            name='taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohotaxes'),
        ),
        migrations.AlterField(
            model_name='vendorzohobill',
            name='is_tax',
            field=models.CharField(blank=True, choices=[('NOT_APPLICABLE', 'Not Applicable'), ('TCS', 'is_tcs_tax'), ('TDS', 'is_tds_tax')], default='TDS', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='JournalBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('billmunshiName', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='bills/', validators=[apps.module.zoho.models.validate_file_extension])),
                ('fileType', models.CharField(blank=True, choices=[('Single Invoice/File', 'Single Invoice/File'), ('Multiple Invoice/File', 'Multiple Invoice/File')], default='Single Invoice/File', max_length=100, null=True)),
                ('analysed_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analysed', 'Analysed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10)),
                ('process', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_journal_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Bill',
                'verbose_name_plural': 'Journal Bills',
            },
        ),
        migrations.CreateModel(
            name='JournalZohoBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('cgst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('sgst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('note', models.CharField(blank=True, default='Enter Your Description', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
                ('selectBill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.journalbill')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohovendor')),
            ],
            options={
                'verbose_name': 'Analysed Journal Bill',
                'verbose_name_plural': 'Analysed Journal Bills',
            },
        ),
        migrations.CreateModel(
            name='JournalZohoProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_details', models.CharField(blank=True, max_length=2000, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohochartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohovendor')),
                ('zohoBill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='zoho.journalzohobill')),
            ],
            options={
                'verbose_name': 'Journal Analysed Bill Product',
                'verbose_name_plural': 'Journal Analysed Bill Products',
            },
        ),
    ]
