# Generated by Django 5.2.5 on 2025-10-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0005_remove_expensezohoproduct_debit_or_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorzohobill',
            name='is_tax',
            field=models.CharField(blank=True, choices=[('NOT_APPLICABLE', 'Not Applicable'), ('TCS', 'is_tcs_tax'), ('TDS', 'is_tds_tax')], default='NOT_APPLICABLE', max_length=100, null=True),
        ),
    ]
