# Generated by Django 5.2.5 on 2025-10-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0006_alter_vendorzohobill_is_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensezohobill',
            name='chart_of_accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohochartofaccount'),
        ),
    ]
