# Generated by Django 5.2.5 on 2025-10-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0007_expensezohobill_chart_of_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensezohoproduct',
            name='itc_eligibility',
        ),
        migrations.RemoveField(
            model_name='expensezohoproduct',
            name='reverse_charge_tax_id',
        ),
    ]
