# Generated by Django 5.2.5 on 2025-10-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0008_remove_expensezohoproduct_itc_eligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohovendor',
            name='gst_treatment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
