# Generated by Django 5.2.5 on 2025-10-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0009_zohovendor_gst_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalzohoproduct',
            name='vendor',
        ),
        migrations.AddField(
            model_name='journalzohoproduct',
            name='taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohotaxes'),
        ),
    ]
