# Generated by Django 5.2.5 on 2025-10-27 18:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0010_remove_journalzohoproduct_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalzohoproduct',
            name='taxes',
        ),
        migrations.AddField(
            model_name='journalzohobill',
            name='cgst_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cgst_tally_expense_analysed_bills', to='zoho.zohochartofaccount'),
        ),
        migrations.AddField(
            model_name='journalzohobill',
            name='cgst_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='journalzohobill',
            name='igst_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='igst_tally_expense_analysed_bills', to='zoho.zohochartofaccount'),
        ),
        migrations.AddField(
            model_name='journalzohobill',
            name='igst_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='journalzohobill',
            name='sgst_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgst_tally_expense_analysed_bills', to='zoho.zohochartofaccount'),
        ),
        migrations.AddField(
            model_name='journalzohobill',
            name='sgst_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='journalzohobill',
            name='vendor_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='journalzohobill',
            name='vendor_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_tally_expense_analysed_bills', to='zoho.zohochartofaccount'),
        ),
        migrations.AddField(
            model_name='journalzohobill',
            name='vendor_debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalzohoproduct',
            name='debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10, null=True),
        ),
    ]
