# Generated by Django 5.2.5 on 2025-11-02 07:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0011_remove_journalzohoproduct_taxes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorzohobill',
            name='adjustment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendorzohobill',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendorzohobill',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('INR', 'INR'), ('Percentage', 'Percentage')], default='INR', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorzohobill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
