# Generated by Django 5.2.5 on 2025-11-02 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0012_vendorzohobill_adjustment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorzohobill',
            name='adjustment_description',
            field=models.CharField(blank=True, default='Adjustment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorzohobill',
            name='discount_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_bills', to='zoho.zohochartofaccount'),
        ),
        migrations.AlterField(
            model_name='vendorzohobill',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('INR', 'INR'), ('Percentage', 'Percentage')], default='Percentage', max_length=20, null=True),
        ),
    ]
