# Generated by Django 5.2.5 on 2025-11-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0013_vendorzohobill_adjustment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorzohobill',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('INR', 'INR (Flat Amount)'), ('Percentage', 'Percentage')], default='Percentage', max_length=20, null=True),
        ),
    ]
