# Generated by Django 5.2.5 on 2025-11-02 08:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0014_alter_vendorzohobill_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorzohobill',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='User-entered discount value (percentage or flat amount)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorzohobill',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Calculated discount amount in INR (auto-calculated)', max_digits=12, null=True),
        ),
    ]
