# Generated by Django 5.2.5 on 2025-11-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0015_vendorzohobill_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensezohobill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalzohobill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
