# Generated by Django 5.2.5 on 2025-12-20 16:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationapikey_api_key_value_gen'),
        ('zoho', '0016_expensezohobill_due_date_journalzohobill_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensezohobill',
            name='consolidate',
            field=models.BooleanField(default=False, help_text='If True, sync as single consolidated expense entry. If False, sync all individual entries.'),
        ),
        migrations.AddField(
            model_name='journalzohobill',
            name='consolidate',
            field=models.BooleanField(default=False, help_text='If True, sync as single consolidated journal entry. If False, sync all individual entries.'),
        ),
        migrations.AddField(
            model_name='vendorzohobill',
            name='consolidate',
            field=models.BooleanField(default=False, help_text='If True, sync as single consolidated line item. If False, sync all individual line items.'),
        ),
        migrations.CreateModel(
            name='ExpenseZohoConsolidatedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('consolidated_item_details', models.TextField(blank=True, default='Multiple expense entries consolidated', help_text='Description for the consolidated expense entry', null=True)),
                ('consolidated_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total consolidated amount', max_digits=15, null=True)),
                ('original_entries_count', models.IntegerField(default=0, help_text='Number of original expense entries that were consolidated')),
                ('consolidation_notes', models.TextField(blank=True, help_text='Notes about how consolidation was performed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_of_accounts', models.ForeignKey(blank=True, help_text='Primary chart of accounts for consolidated entry', null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohochartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
                ('taxes', models.ForeignKey(blank=True, help_text='Tax applied to consolidated entry (highest tax rate or most common)', null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohotaxes')),
                ('zohoBill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_product', to='zoho.expensezohobill')),
            ],
            options={
                'verbose_name': 'Consolidated Expense Product',
                'verbose_name_plural': 'Consolidated Expense Products',
            },
        ),
        migrations.CreateModel(
            name='JournalZohoConsolidatedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('consolidated_item_details', models.TextField(blank=True, default='Multiple journal entries consolidated', help_text='Description for the consolidated journal entry', null=True)),
                ('consolidated_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total consolidated amount', max_digits=15, null=True)),
                ('debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', help_text='Transaction type for consolidated entry', max_length=10, null=True)),
                ('original_entries_count', models.IntegerField(default=0, help_text='Number of original journal entries that were consolidated')),
                ('consolidation_notes', models.TextField(blank=True, help_text='Notes about how consolidation was performed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_of_accounts', models.ForeignKey(blank=True, help_text='Primary chart of accounts for consolidated entry', null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohochartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
                ('zohoBill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_product', to='zoho.journalzohobill')),
            ],
            options={
                'verbose_name': 'Consolidated Journal Product',
                'verbose_name_plural': 'Consolidated Journal Products',
            },
        ),
        migrations.CreateModel(
            name='VendorZohoConsolidatedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('consolidated_item_name', models.CharField(blank=True, default='Multiple items consolidated', help_text='Description for the consolidated line item', max_length=1000, null=True)),
                ('consolidated_item_details', models.TextField(blank=True, help_text='Detailed breakdown of consolidated items', null=True)),
                ('total_quantity', models.DecimalField(blank=True, decimal_places=2, default=Decimal('1'), help_text='Total quantity of all items (usually 1 for consolidated)', max_digits=12, null=True)),
                ('consolidated_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount as rate for consolidated item', max_digits=15, null=True)),
                ('consolidated_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total consolidated amount', max_digits=15, null=True)),
                ('itc_eligibility', models.CharField(blank=True, choices=[('eligible', 'Eligible'), ('ineligible_section17', 'Ineligible Section17'), ('ineligible_others', 'Ineligible Others')], default='eligible', max_length=100, null=True)),
                ('reverse_charge_tax_id', models.BooleanField(default=False)),
                ('original_items_count', models.IntegerField(default=0, help_text='Number of original line items that were consolidated')),
                ('consolidation_notes', models.TextField(blank=True, help_text='Notes about how consolidation was performed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_of_accounts', models.ForeignKey(blank=True, help_text='Primary chart of accounts for consolidated item', null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohochartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_%(class)ss', to='organizations.organization')),
                ('taxes', models.ForeignKey(blank=True, help_text='Tax applied to consolidated item (highest tax rate or most common)', null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohotaxes')),
                ('zohoBill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_product', to='zoho.vendorzohobill')),
            ],
            options={
                'verbose_name': 'Consolidated Vendor Product',
                'verbose_name_plural': 'Consolidated Vendor Products',
            },
        ),
    ]
