# Generated by Django 5.2.5 on 2025-12-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0017_expensezohobill_consolidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensezohoconsolidatedproduct',
            name='zohoBill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_products', to='zoho.expensezohobill'),
        ),
        migrations.AlterField(
            model_name='journalzohoconsolidatedproduct',
            name='zohoBill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_products', to='zoho.journalzohobill'),
        ),
        migrations.AlterField(
            model_name='vendorzohoconsolidatedproduct',
            name='zohoBill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_products', to='zoho.vendorzohobill'),
        ),
    ]
