# Generated by Django 5.2.5 on 2025-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0018_alter_expensezohoconsolidatedproduct_zohobill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohocredentials',
            name='is_connected',
            field=models.BooleanField(default=False, help_text='Whether the Zoho Books integration is fully connected and functional'),
        ),
    ]
