# Generated by Django 5.2.5 on 2026-01-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0019_zohocredentials_is_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohovendor',
            name='contactId',
            field=models.CharField(max_length=100),
        ),
    ]
