# Generated by Django 5.2.5 on 2026-02-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0021_vendorbill_bill_belong_your_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensebill',
            name='bill_belong_your_org',
            field=models.BooleanField(default=False, help_text='Whether this bill belongs to your organization'),
        ),
        migrations.AddField(
            model_name='expensebill',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the bill', null=True),
        ),
        migrations.AddField(
            model_name='expensebill',
            name='duplicate_description',
            field=models.TextField(blank=True, help_text='Description of duplicate matches found', null=True),
        ),
        migrations.AddField(
            model_name='expensebill',
            name='duplicate_matched_bills',
            field=models.JSONField(blank=True, default=list, help_text='List of matched duplicate bill details'),
        ),
        migrations.AddField(
            model_name='expensebill',
            name='duplicate_score',
            field=models.FloatField(blank=True, help_text='Similarity score with duplicate bills (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='expensebill',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='Whether this bill is identified as a potential duplicate'),
        ),
        migrations.AddField(
            model_name='expensebill',
            name='is_processing',
            field=models.BooleanField(default=False, help_text='Whether this bill is currently being processed in background'),
        ),
        migrations.AddField(
            model_name='expensebill',
            name='job_id',
            field=models.CharField(blank=True, help_text='Background job ID for tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensebill',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='journalbill',
            name='bill_belong_your_org',
            field=models.BooleanField(default=False, help_text='Whether this bill belongs to your organization'),
        ),
        migrations.AddField(
            model_name='journalbill',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the bill', null=True),
        ),
        migrations.AddField(
            model_name='journalbill',
            name='duplicate_description',
            field=models.TextField(blank=True, help_text='Description of duplicate matches found', null=True),
        ),
        migrations.AddField(
            model_name='journalbill',
            name='duplicate_matched_bills',
            field=models.JSONField(blank=True, default=list, help_text='List of matched duplicate bill details'),
        ),
        migrations.AddField(
            model_name='journalbill',
            name='duplicate_score',
            field=models.FloatField(blank=True, help_text='Similarity score with duplicate bills (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='journalbill',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='Whether this bill is identified as a potential duplicate'),
        ),
        migrations.AddField(
            model_name='journalbill',
            name='is_processing',
            field=models.BooleanField(default=False, help_text='Whether this bill is currently being processed in background'),
        ),
        migrations.AddField(
            model_name='journalbill',
            name='job_id',
            field=models.CharField(blank=True, help_text='Background job ID for tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journalbill',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
    ]
