# Generated by Django 6.0.7 on 2026-07-31 06:43
"""Guarantee unique bill names for newly created bills.

See the matching tally migration for the full rationale: the constraint is
partial, so existing bills keep their names untouched, and the repair step only
covers rows created at or after ``CUTOFF``.

The ``AlterField`` operations on ``process`` are unrelated pre-existing model
drift (a ``help_text`` change only) that Django folded into this migration.
"""

import datetime
import re

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count

CUTOFF = datetime.datetime(2026, 7, 31, 0, 0, tzinfo=datetime.timezone.utc)

NAME_FIELD = "billmunshiName"
TARGETS = ["ExpenseBill", "JournalBill", "VendorBill"]


def _next_free_name(Model, org_id, taken_name, issued):
    """Return the next unused name sharing ``taken_name``'s prefix.

    Scans ALL rows for that prefix, not just post-cutoff ones, so a repaired
    name can never land on top of a historical bill.
    """
    match = re.match(r"^(.*?)(\d+)$", taken_name)
    prefix = match.group(1) if match else taken_name

    pattern = re.compile(rf"{re.escape(prefix)}(\d+)$")
    highest = 0
    existing = Model.objects.filter(
        organization_id=org_id,
        **{f"{NAME_FIELD}__startswith": prefix},
    ).values_list(NAME_FIELD, flat=True)

    for name in list(existing) + sorted(issued):
        if not name:
            continue
        found = pattern.match(name)
        if found:
            highest = max(highest, int(found.group(1)))

    return f"{prefix}{highest + 1:05d}"


def repair_post_cutoff_duplicates(apps, schema_editor):
    for model_name in TARGETS:
        Model = apps.get_model("zoho", model_name)
        recent = Model.objects.filter(created_at__gte=CUTOFF)

        groups = (
            recent.exclude(**{f"{NAME_FIELD}__isnull": True})
            .exclude(**{NAME_FIELD: ""})
            .values("organization_id", NAME_FIELD)
            .annotate(total=Count("id"))
            .filter(total__gt=1)
        )

        for group in groups:
            org_id = group["organization_id"]
            clashing = group[NAME_FIELD]
            rows = list(
                recent.filter(
                    organization_id=org_id, **{NAME_FIELD: clashing}
                ).order_by("created_at", "id")
            )
            issued = set()
            for row in rows[1:]:  # oldest of the group keeps its name
                new_name = _next_free_name(Model, org_id, clashing, issued)
                issued.add(new_name)
                setattr(row, NAME_FIELD, new_name)
                row.save(update_fields=[NAME_FIELD])


def noop_reverse(apps, schema_editor):
    """Renaming cannot be undone — the original values are not retained."""


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_gst_number'),
        ('zoho', '0024_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(repair_post_cutoff_duplicates, noop_reverse),
        migrations.AlterField(
            model_name='expensebill',
            name='process',
            field=models.BooleanField(default=False, help_text='HAS-been-analysed flag: True once AI analysis has produced ``analysed_data`` and an ``analysed_headers`` row. Semantically means "analysis done", not "currently processing". For the in-progress state see ``is_processing``. Historical name — keep for backwards compat.'),
        ),
        migrations.AlterField(
            model_name='journalbill',
            name='process',
            field=models.BooleanField(default=False, help_text='HAS-been-analysed flag: True once AI analysis has produced ``analysed_data`` and an ``analysed_headers`` row. Semantically means "analysis done", not "currently processing". For the in-progress state see ``is_processing``. Historical name — keep for backwards compat.'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='process',
            field=models.BooleanField(default=False, help_text='HAS-been-analysed flag: True once AI analysis has produced ``analysed_data`` and an ``analysed_headers`` row. Semantically means "analysis done", not "currently processing". For the in-progress state see ``is_processing``. Historical name — keep for backwards compat.'),
        ),
        migrations.AddConstraint(
            model_name='expensebill',
            constraint=models.UniqueConstraint(condition=models.Q(('created_at__gte', datetime.datetime(2026, 7, 31, 0, 0, tzinfo=datetime.timezone.utc))), fields=('organization', 'billmunshiName'), name='uniq_zoho_expensebill_org_name'),
        ),
        migrations.AddConstraint(
            model_name='journalbill',
            constraint=models.UniqueConstraint(condition=models.Q(('created_at__gte', datetime.datetime(2026, 7, 31, 0, 0, tzinfo=datetime.timezone.utc))), fields=('organization', 'billmunshiName'), name='uniq_zoho_journalbill_org_name'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.UniqueConstraint(condition=models.Q(('created_at__gte', datetime.datetime(2026, 7, 31, 0, 0, tzinfo=datetime.timezone.utc))), fields=('organization', 'billmunshiName'), name='uniq_zoho_vendorbill_org_name'),
        ),
    ]
