# Generated by Django 6.0.7 on 2026-07-31 05:18

import apps.common.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('accounting_software', models.CharField(choices=[('zoho', 'Zoho Books'), ('tally', 'Tally'), ('both', 'Both (Zoho Books & Tally)'), ('other', 'Other / Not sure')], max_length=20)),
                ('email', models.EmailField(help_text='Work email. Personal mailboxes (Gmail, Yahoo, …) are rejected.', max_length=254, unique=True, validators=[apps.common.validators.validate_business_email])),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal sales notes.')),
            ],
            options={
                'verbose_name': 'Demo request',
                'verbose_name_plural': 'Demo requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
