# Generated by Django 4.2.16 on 2026-09-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_demorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
