# Generated by Django 4.2.16 on 2026-09-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_bio_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_accounting_software',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_designation',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_organization_gst',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Organization GST No.'),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_organization_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
