# Generated by hand (no Django install available in this environment) to
# match the style of apps/organizations/migrations/0001_initial.py.
# Verify with `python3 manage.py makemigrations --check support` once
# apps.support is wired into LOCAL_APPS — this should produce no diff.

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('question', 'Question'), ('billing', 'Billing'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('page_url', models.URLField(blank=True, default='', max_length=500)),
                ('browser', models.CharField(blank=True, default='', max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_email', models.EmailField(blank=True, default='', max_length=254)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note — visible to admins only, never emailed to the submitter.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('receive_new', models.BooleanField(default=True, help_text='Notify this address when a new ticket is created.')),
                ('receive_reply', models.BooleanField(default=False, help_text='Notify this address when a submitter replies to a ticket.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
