# Generated by Django 4.2.16 on 2026-09-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='source',
            field=models.CharField(choices=[('ticket', 'Support ticket'), ('chat', 'Support chat')], default='ticket', max_length=10),
        ),
    ]
