# Generated by Django 5.2.5 on 2025-08-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmodule',
            options={},
        ),
        migrations.RenameField(
            model_name='organizationmodule',
            old_name='is_enabled',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='organizationmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.module'),
        ),
        migrations.AlterField(
            model_name='organizationmodule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='organizations.organization'),
        ),
    ]
