# Generated by Django 5.2.5 on 2025-08-09 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationapikey',
            name='api_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_link', to='rest_framework_api_key.apikey'),
        ),
        migrations.AddField(
            model_name='organizationapikey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_org_api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationapikey',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='orgmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationapikey',
            unique_together={('api_key', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='orgmembership',
            unique_together={('organization', 'user')},
        ),
    ]
