# Generated by Django 5.2.5 on 2025-08-11 18:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_modules', to='organizations.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_modules', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'module_id'),
                'unique_together': {('organization', 'module')},
            },
        ),
    ]
