# Generated by Django 5.2.5 on 2025-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organizationmodule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('CONSULTANT', 'Consultant')], default='MANAGER', max_length=10),
        ),
    ]
