# Generated by Django 5.2.5 on 2025-10-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_orgmembership_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationapikey',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='organizationapikey',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='organizations.organization'),
        ),
    ]
