# Generated by Django 5.2.5 on 2025-10-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organizationapikey_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationapikey',
            name='api_key_value_gen',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
