# Generated by Django 5.2.5 on 2026-02-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationapikey_api_key_value_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST registration number', max_length=15, null=True),
        ),
    ]
